name: 'Conversational release action'
description: 'Release Quarkus by conversing with a GitHub Action'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false
  interaction-comment:
    description: 'Optional interaction comment'
    required: false
outputs:
  branch:
    value: ${{ steps.action.outputs.branch }}
  qualifier:
    value: ${{ steps.action.outputs.qualifier }}
  major:
    value: ${{ steps.action.outputs.major }}
  version:
    value: ${{ steps.action.outputs.version }}
  jdk:
    value: ${{ steps.action.outputs.jdk }}
  status:
    value: ${{ steps.action.outputs.status }}
  current-step:
    value: ${{ steps.action.outputs.current-step }}
  current-step-status:
    value: ${{ steps.action.outputs.current-step-status }}
  workflow-run-id:
    value: ${{ steps.action.outputs.workflow-run-id }}
  interaction-comment:
    value: ${{ steps.action.outputs.interaction-comment }}
runs:
  using: "composite"
  steps:
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/quarkusio/conversational-release-action/' --repos 'mavencentral' io.quarkus.bot:conversational-release-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
