name: 'Conversational release action'
description: 'Release Quarkus by conversing with a GitHub Action'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false
  interaction-comment:
    description: 'Optional interaction comment'
    required: false
outputs:
  workflow-run-id:
    value: ${{ steps.action.outputs.workflow-run-id }}
  interaction-comment:
    value: ${{ steps.action.outputs.interaction-comment }}
runs:
  using: "composite"
  steps:
    - id: install-jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - id: action
      run: ~/.jbang/bin/jbang --repos 'github=https://maven.pkg.github.com/quarkusio/conversational-release-action/' --repos 'mavencentral' io.quarkus.bot:conversational-release-action:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
